### ISSUE TITLE
Update to latest open release

### ISSUE THREAD

**Issue by EliJDonahue** [ArasLabs/cui-shortcut#1]
Test and update to support Aras 11 SP12.

**Comment by PremalBhagat** [comment]
Tested to support Aras 11 SP12.
Built Using: Aras 11.0 SP12 Browsers Tested: Internet Explorer 11, Firefox 62, Chrome 69
The package is compatible with latest open release Aras 11 SP12

**Comment by cgillis-aras** [comment]
Fixed in 51766a5ac5a8404ea4d422003d0621b4075719de when I added new examples
